# Generated by Django 3.2.4 on 2021-07-24 02:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('course', '0002_auto_20210717_1458'),
        ('question', '0003_auto_20210718_1404'),
        ('agent', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('total_questions', models.IntegerField(default=0)),
                ('mark_per_question', models.IntegerField(default=1)),
                ('minus_mark_per_question', models.IntegerField(default=-1)),
                ('status', models.CharField(choices=[('CREATED', 'CREATED'), ('STARTED', 'STARTED'), ('ENDED', 'ENDED'), ('SUSPENDED', 'SUSPENDED')], default='CREATED', max_length=50)),
                ('course', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='exams', to='course.course')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_list', to='agent.agent')),
                ('questions', models.ManyToManyField(null=True, related_name='exam', to='question.Question')),
            ],
        ),
    ]
