# Generated by Django 3.2.4 on 2021-08-22 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participant',
            name='time_taken',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='participant',
            name='user_answer',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
