# Generated by Django 3.2.4 on 2021-07-17 09:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('agent', '0001_initial'),
        ('student', '0004_alter_student_created'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=255)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('status', models.CharField(choices=[('CREATED', 'CREATED'), ('STARTED', 'STARTED'), ('ENDED', 'ENDED'), ('SUSPENDED', 'SUSPENDED')], max_length=50)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_courses', to='agent.agent')),
                ('students', models.ManyToManyField(to='student.Student')),
            ],
        ),
    ]
