# Generated by Django 3.2.4 on 2021-07-05 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customauth', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'ADMIN'), ('AGENT', 'AGENT'), ('STUDENT', 'STUDENT')], default='STUDENT', max_length=125),
        ),
    ]
