# Generated by Django 3.2.4 on 2021-07-18 14:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0002_option_key'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='option',
            name='key',
        ),
        migrations.AlterField(
            model_name='option',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='question.question'),
        ),
    ]
