# Generated by Django 3.2.4 on 2021-08-22 02:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customauth', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Agent',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='customauth.myuser')),
                ('name', models.CharField(max_length=255)),
                ('phone_number', models.CharField(max_length=12)),
                ('address_state', models.CharField(max_length=255)),
                ('address_city', models.CharField(max_length=255)),
                ('address_pin', models.CharField(max_length=6)),
            ],
        ),
    ]
