# Generated by Django 3.2.4 on 2021-08-01 11:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('student', '0004_alter_student_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='added_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='agent_students', to=settings.AUTH_USER_MODEL),
        ),
    ]
